--
-- PostgreSQL database dump
--

\restrict B3NuJMt2lLulQeqOF87bSVgLzKHy7MzQdeffQswvK0b8xX8Sb51tkPWd2Q0Xsw8

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: exception_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exception_report (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    reported_by bigint NOT NULL,
    resolved_at timestamp(6) with time zone,
    session_id bigint,
    description text NOT NULL,
    resolution_note text,
    status character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT exception_report_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying])::text[]))),
    CONSTRAINT exception_report_type_check CHECK (((type)::text = ANY ((ARRAY['LOST_TICKET'::character varying, 'WRONG_PLATE'::character varying, 'OVERTIME'::character varying, 'WRONG_ZONE'::character varying])::text[])))
);


--
-- Name: exception_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exception_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exception_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    rating smallint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    comment character varying(500)
);


--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: floor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.floor (
    level integer NOT NULL,
    building_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    vehicle_type_id bigint,
    name character varying(255) NOT NULL
);


--
-- Name: floor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.floor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.floor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: monthly_pass; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monthly_pass (
    valid_from date NOT NULL,
    valid_until date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    payment_id bigint,
    user_id bigint NOT NULL,
    vehicle_type_id bigint NOT NULL,
    license_plate character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT monthly_pass_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: monthly_pass_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.monthly_pass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monthly_pass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_building; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parking_building (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    address character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: parking_building_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parking_building ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_building_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parking_session (
    amount_charged numeric(38,2),
    auto_allocated boolean NOT NULL,
    deposit_credit numeric(38,2),
    from_reservation boolean NOT NULL,
    check_in_at timestamp(6) with time zone NOT NULL,
    check_out_at timestamp(6) with time zone,
    id bigint NOT NULL,
    slot_id bigint NOT NULL,
    user_id bigint,
    vehicle_type_id bigint NOT NULL,
    license_plate character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    ticket_code character varying(255) NOT NULL,
    allocation_score jsonb,
    CONSTRAINT parking_session_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'AWAITING_PAYMENT'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: parking_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parking_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_slot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parking_slot (
    created_at timestamp(6) with time zone NOT NULL,
    floor_id bigint NOT NULL,
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT parking_slot_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'OCCUPIED'::character varying, 'RESERVED'::character varying, 'MAINTENANCE'::character varying, 'LOCKED'::character varying])::text[])))
);


--
-- Name: parking_slot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parking_slot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_token (
    used boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(64) NOT NULL
);


--
-- Name: password_reset_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    amount numeric(38,2) NOT NULL,
    penalty_amount numeric(38,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    paid_at timestamp(6) with time zone,
    processed_by_staff_id bigint,
    session_id bigint,
    voided_at timestamp(6) with time zone,
    description character varying(255),
    gateway_ref character varying(255),
    gateway_response_code character varying(255),
    gateway_txn_no character varying(255),
    method character varying(255),
    status character varying(255) NOT NULL,
    void_reason character varying(255),
    CONSTRAINT payment_method_check CHECK (((method)::text = ANY ((ARRAY['CASH'::character varying, 'ONLINE'::character varying, 'VNPAY'::character varying])::text[]))),
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'VOIDED'::character varying])::text[])))
);


--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pricing_policy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pricing_policy (
    daily_cap numeric(38,2),
    grace_minutes integer NOT NULL,
    is_active boolean NOT NULL,
    monthly_pass_price numeric(38,2),
    peak_multiplier numeric(38,2) NOT NULL,
    rate_per_hour numeric(38,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    vehicle_type_id bigint NOT NULL
);


--
-- Name: pricing_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pricing_policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pricing_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation (
    deposit_amount numeric(38,2),
    building_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    deposit_payment_id bigint,
    hold_until timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    reserved_start timestamp(6) with time zone,
    slot_id bigint,
    user_id bigint NOT NULL,
    vehicle_type_id bigint NOT NULL,
    license_plate character varying(255) NOT NULL,
    reservation_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    allocation_score jsonb,
    CONSTRAINT reservation_reservation_type_check CHECK (((reservation_type)::text = ANY ((ARRAY['FREE'::character varying, 'PAID'::character varying])::text[]))),
    CONSTRAINT reservation_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'FULFILLED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'STAFF'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle_type (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: vehicle_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicle_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exception_report exception_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exception_report
    ADD CONSTRAINT exception_report_pkey PRIMARY KEY (id);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: feedback feedback_session_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_session_id_key UNIQUE (session_id);


--
-- Name: floor floor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.floor
    ADD CONSTRAINT floor_pkey PRIMARY KEY (id);


--
-- Name: monthly_pass monthly_pass_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monthly_pass
    ADD CONSTRAINT monthly_pass_pkey PRIMARY KEY (id);


--
-- Name: parking_building parking_building_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_building
    ADD CONSTRAINT parking_building_pkey PRIMARY KEY (id);


--
-- Name: parking_session parking_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_session
    ADD CONSTRAINT parking_session_pkey PRIMARY KEY (id);


--
-- Name: parking_session parking_session_ticket_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_session
    ADD CONSTRAINT parking_session_ticket_code_key UNIQUE (ticket_code);


--
-- Name: parking_slot parking_slot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_slot
    ADD CONSTRAINT parking_slot_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: password_reset_token password_reset_token_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_token_key UNIQUE (token);


--
-- Name: payment payment_gateway_ref_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_gateway_ref_key UNIQUE (gateway_ref);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: payment payment_session_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_session_id_key UNIQUE (session_id);


--
-- Name: pricing_policy pricing_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_policy
    ADD CONSTRAINT pricing_policy_pkey PRIMARY KEY (id);


--
-- Name: pricing_policy pricing_policy_vehicle_type_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_policy
    ADD CONSTRAINT pricing_policy_vehicle_type_id_key UNIQUE (vehicle_type_id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vehicle_type vehicle_type_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_type
    ADD CONSTRAINT vehicle_type_name_key UNIQUE (name);


--
-- Name: vehicle_type vehicle_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle_type
    ADD CONSTRAINT vehicle_type_pkey PRIMARY KEY (id);


--
-- Name: parking_session fk47dwqx0uoltsp7fdpphhelcf2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_session
    ADD CONSTRAINT fk47dwqx0uoltsp7fdpphhelcf2 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: exception_report fk4dpflkm24rf8id87v75dv3it1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exception_report
    ADD CONSTRAINT fk4dpflkm24rf8id87v75dv3it1 FOREIGN KEY (session_id) REFERENCES public.parking_session(id);


--
-- Name: floor fk4ud3una9m5sg56d0ga0mo9gi2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.floor
    ADD CONSTRAINT fk4ud3una9m5sg56d0ga0mo9gi2 FOREIGN KEY (building_id) REFERENCES public.parking_building(id);


--
-- Name: password_reset_token fk83nsrttkwkb6ym0anu051mtxn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fk83nsrttkwkb6ym0anu051mtxn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: monthly_pass fk9ei7osf0mchkomvsgh82uxvo3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monthly_pass
    ADD CONSTRAINT fk9ei7osf0mchkomvsgh82uxvo3 FOREIGN KEY (payment_id) REFERENCES public.payment(id);


--
-- Name: parking_session fk9n8d2t145gbyg12ca5clbajg6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_session
    ADD CONSTRAINT fk9n8d2t145gbyg12ca5clbajg6 FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_type(id);


--
-- Name: pricing_policy fkb79jgf0y6tk2q1edjeb7qw0rd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_policy
    ADD CONSTRAINT fkb79jgf0y6tk2q1edjeb7qw0rd FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_type(id);


--
-- Name: exception_report fkdw7ued6381oxly4xl24asikt6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exception_report
    ADD CONSTRAINT fkdw7ued6381oxly4xl24asikt6 FOREIGN KEY (reported_by) REFERENCES public.users(id);


--
-- Name: floor fkfi1u22q8vtb624t4nyesy4s8v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.floor
    ADD CONSTRAINT fkfi1u22q8vtb624t4nyesy4s8v FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_type(id);


--
-- Name: parking_slot fkg6ltredxjoe7d2p0qprxk1ywt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_slot
    ADD CONSTRAINT fkg6ltredxjoe7d2p0qprxk1ywt FOREIGN KEY (floor_id) REFERENCES public.floor(id);


--
-- Name: parking_session fkg8hxva0a5i7948p3qplfmuldd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parking_session
    ADD CONSTRAINT fkg8hxva0a5i7948p3qplfmuldd FOREIGN KEY (slot_id) REFERENCES public.parking_slot(id);


--
-- Name: monthly_pass fkgcd6xix2xykkle6llv7qix06h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monthly_pass
    ADD CONSTRAINT fkgcd6xix2xykkle6llv7qix06h FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reservation fkhblw0yo84x1ubat3hgv8j3j8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkhblw0yo84x1ubat3hgv8j3j8g FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_type(id);


--
-- Name: payment fkm0k1f29dbn99astv4rumlwslb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkm0k1f29dbn99astv4rumlwslb FOREIGN KEY (session_id) REFERENCES public.parking_session(id);


--
-- Name: reservation fkn7uvxakyqyl9s8gmq1elm22f8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkn7uvxakyqyl9s8gmq1elm22f8 FOREIGN KEY (slot_id) REFERENCES public.parking_slot(id);


--
-- Name: payment fko273j4cvdsa1glguxd961s50l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fko273j4cvdsa1glguxd961s50l FOREIGN KEY (processed_by_staff_id) REFERENCES public.users(id);


--
-- Name: feedback fkokriwr9rra8qs90alwbcna6hn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fkokriwr9rra8qs90alwbcna6hn FOREIGN KEY (session_id) REFERENCES public.parking_session(id);


--
-- Name: monthly_pass fkout6q223okepxr74mcc5t5c16; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monthly_pass
    ADD CONSTRAINT fkout6q223okepxr74mcc5t5c16 FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_type(id);


--
-- Name: reservation fkpwil66nuye097gu92pgbtkboe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkpwil66nuye097gu92pgbtkboe FOREIGN KEY (building_id) REFERENCES public.parking_building(id);


--
-- Name: feedback fkpwwmhguqianghvi1wohmtsm8l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fkpwwmhguqianghvi1wohmtsm8l FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reservation fkrea93581tgkq61mdl13hehami; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkrea93581tgkq61mdl13hehami FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reservation fksopg4mynp0yoo69ymuo31ck7m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fksopg4mynp0yoo69ymuo31ck7m FOREIGN KEY (deposit_payment_id) REFERENCES public.payment(id);


--
-- PostgreSQL database dump complete
--

\unrestrict B3NuJMt2lLulQeqOF87bSVgLzKHy7MzQdeffQswvK0b8xX8Sb51tkPWd2Q0Xsw8

